# Generated by Django 4.2.16 on 2025-05-26 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_keyword_post_keywords'),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvoidedKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='interested_genres',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='lifestyle',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='preferred_reading_style',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='lifestyles',
            field=models.ManyToManyField(to='accounts.lifestylekeyword'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='preferred_reading_styles',
            field=models.ManyToManyField(to='accounts.readingstyle'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='avoided_genres',
            field=models.ManyToManyField(to='books.category'),
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='avoided_keywords',
        ),
        migrations.AddField(
            model_name='userpreference',
            name='avoided_keywords',
            field=models.ManyToManyField(to='accounts.avoidedkeyword'),
        ),
    ]
