# Generated by Django 4.2.16 on 2025-05-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_keyword_post_keywords'),
        ('accounts', '0003_avoidedkeyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='interested_genres',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='books.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='avoided_genres',
            field=models.ManyToManyField(blank=True, related_name='avoided_by', to='books.category'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='avoided_keywords',
            field=models.ManyToManyField(blank=True, to='accounts.avoidedkeyword'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='lifestyles',
            field=models.ManyToManyField(blank=True, to='accounts.lifestylekeyword'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_reading_styles',
            field=models.ManyToManyField(blank=True, to='accounts.readingstyle'),
        ),
    ]
