# Generated by Django 4.2.16 on 2025-05-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingstatus',
            name='stop_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
